### ISSUE TITLE
Focus change seems unmapped

### ISSUE THREAD

**Issue by shepard8** [Armael/ocaml-i3ipc#1]
Hello,

Unless I don't understand something in the architecture of ocaml-i3ipc, I think that the Focus event is unmapped in function window_change_of_yojson.

I'd add a pattern ```| `String "focus" -> Result.Ok Focus```.

**Comment by Armael** [comment]
FYI I just submitted a new release that includes your fix (https://github.com/ocaml/opam-repository/pull/12231).

**Comment by shepard8** [comment]
Woah that was pretty fast! :+1:
