### ISSUE TITLE
Keep this library up to date

### ISSUE THREAD

**Issue by pdonadeo** [Armael/ocaml-i3ipc#3]
Just a question: do you think to update this library to build with the latest Lwt?

**Comment by Armael** [comment]
Thanks for the interest!
I don't have much time right now, but I would be happy to review a PR that updates the library, if you feel motivated.

**Comment by pdonadeo** [comment]
Yes, I'm interested in keeping the library up to date because I like OCaml, I like i3 and your library is simple and tidy.

My "plan", of course if you agree, is this:
  - [x] compiling the library with the latest Lwt/OCaml
  - [x] porting from OASIS to dune (optional but IMHO it's advisable)
  - [ ] adding the missing events/commands/data structures, for example [window_properties](https://i3wm.org/docs/ipc.html#_tree_reply)

What do you think?

**Comment by Armael** [comment]
Sounds good! I agree with all the items.

**Comment by pdonadeo** [comment]
Ok, first step accomplished.

**Comment by Armael** [comment]
FYI, I went ahead and implemented items 1 and 2 (porting the build to dune, mostly), and published a new release (https://github.com/ocaml/opam-repository/pull/14174).
I really won't have time for the third one, so feel free to work on it.

**Comment by pdonadeo** [comment]
I'm going to try a merge with my work, here: https://github.com/pdonadeo/ocaml-i3ipc/commits/master

**Comment by pdonadeo** [comment]
I just committed on my repo a merge with your upstream changes. I merged (possibly messing up a the history) because I already had a lot of commits.

**Comment by pdonadeo** [comment]
It you agree with my work we can close this issue and I can file a pull request. I'm going to open another issue about the container IDs.

**Comment by Armael** [comment]
Sounds good. Let's discuss on the PR.
