### ISSUE TITLE
The type of container id is probably too small

### ISSUE THREAD

**Issue by pdonadeo** [Armael/ocaml-i3ipc#5]
I found a difference between the output of GET_TREE as obtained by `i3-msg` and the function get_tree, [see this Gist](https://gist.github.com/pdonadeo/d49adfd431d37813e3c2b9ba1d383c10).

The correct window ID is `93862385097088`, while the library result is `169810304l`. I think the int32 is too small and I already have a patch (not committed) to replace the ID with a `Stdint.Uint64.t`.

What do you think?

**Comment by Armael** [comment]
This is a very good point, we should clearly not use int32 here. (u)int64 should work in practice -- but actually, the i3 docs say that the ID is just "a C pointer". So, strictly speaking, it's really platform-specific: on an hypothetical 128 bits architecture, it might not fit in uint64. So I think we should just keep it as a string. It's not like we need a compact representation anyway, I think?

**Comment by pdonadeo** [comment]
You are totally right about the hypothetical 128 bit architecture but using a string is impossible (ok, not really "impossible" but impractical) because the JSON (output of get_tree) contains an integer literal and so it is parsed by yojson. I already have the code working with Uint64... which is 14 lines of code.

I have only to rebase.

**Comment by Armael** [comment]
> the JSON (output of get_tree) contains an integer literal and so it is parsed by yojson

Right, but as far as I can tell from the documentation of `Yojson.Safe`, yojson will return a `Intlit` containing a string if the literal does not fit in an ocaml `int`. So we can just use this string.

**Comment by pdonadeo** [comment]
Just pushed [this](https://github.com/pdonadeo/ocaml-i3ipc/commit/d7f35b7cc0ef406869abfb22cd74f5747e6d9021): the `id` is a string.
