### ISSUE TITLE
Transient_for property is not a string

### ISSUE THREAD

**Issue by Chimrod** [Armael/ocaml-i3ipc#8]
The transient_for property is defined as `string option` in the [source](https://github.com/Armael/ocaml-i3ipc/blob/master/src/i3ipc.ml#L117).

This not according with the data sent by i3 which sent `int` (see example given in [i3 documentation](https://i3wm.org/docs/ipc.html#_tree_reply))

```json
{
 "id": 6875648,
 "name": "root",
 "nodes": [

   {
    "id": 6878320,
    "name": "LVDS1",
    "layout": "output",
    "nodes": [
      {
       "nodes": [
         {
          "id": 6880464,
          "name": "1",
          "orientation": "horizontal",
          "window_properties": {
            "class": "Evince",
            "instance": "evince",
            "title": "Properties",
            "transient_for": 52428808
          }
         }
       ]
      }
    ]
   }
 ]
}
```

**Comment by Armael** [comment]
That looks like a bug indeed, reading the i3 documentation it should be a `int option` as it refers to a X11 window id.

**Comment by Chimrod** [comment]
I've patch your code manually, and I confirm the data is indeed an `int option`

(I've build a [workspace manager](https://github.com/Chimrod/i3_workspaces) on top on your library this is how I've discovered the bug)

**Comment by Armael** [comment]
>(I've build a workspace manager on top on your library this is how I've discovered the bug)

Very cool! That's something I could use myself actually.
I just pushed a commit (a144a070) that should fix the issue. Since it is technically a breaking API change, I'll try to do some more cleanup and then a new release.
