### ISSUE TITLE
Superfluous "num" field in the node type?

### ISSUE THREAD

**Issue by Armael** [Armael/ocaml-i3ipc#9]
https://github.com/Armael/ocaml-i3ipc/blob/master/src/i3ipc.ml#L145

@pdonadeo this looks like a leftover from your refactoring; the specification doesn't mention such a field and it doesn't seem to be produced by i3-msg either.
Do you confirm that we could remove this field?

**Comment by pdonadeo** [comment]
Do you mean the `node_id` type? It is an important part of the TREE reply: https://i3wm.org/docs/ipc.html#_tree_reply

In the documentation it's reported to be an integer but I used a string, the discussion is here: https://github.com/Armael/ocaml-i3ipc/issues/5

**Comment by Armael** [comment]
No, I do mean the `num` field. Sorry, I made some changes in the meantime that messed up the line number. I have updated the link to the code.

**Comment by pdonadeo** [comment]
Ok, I found it. It's undocumented but it **is** part of the reply, at least with the version of i3 I'm using right now: 4.17.

`num` is described as part of the [WORKSPACES reply](https://i3wm.org/docs/ipc.html#_workspaces_reply) but it's actually included in the reply of `GET_TREE`.

You can inspect the output of the command:

```bash
i3-msg -t 'GET_TREE' | python -m json.tool > tree.json
```

here: https://gist.github.com/pdonadeo/fff15dfa1c657a9bfcf1c4bc236f1faf

**Comment by Armael** [comment]
Ah indeed, actually i3-msg does produce it on my computer as well. Thanks for the explanation.

**Comment by Armael** [comment]
Ah indeed, actually i3-msg does produce it on my computer as well. Thanks for the explanation.
